config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  # /sidekiq page

  # authenticate :user, ->(u) { u.admin? } do
  #   mount Sidekiq::Web => '/sideqkic'

  #   namespace :admin do
  #     resources :users
  #     root to: 'users#index'
  #     resources :submissions
  #   end
  # end

  resources :communities do
    resources :subscriptions
  end

  resources :submissions do
    member do
      put 'upvote', to: 'submissions#upvote'
      put 'downvote', to: 'submissions#downvote'
    end

    resources :comments do
      member do
        put 'upvote', to: 'comments#upvote'
        put 'downvote', to: 'comments#downvote'
      end
    end
  end

  get 'submissions/unsubscribe/:unsubscribe_hash' => 'submissions#unsubscribe', as: :comment_unsubscribe
  get :search, controller: :application

  devise_for :users
  root 'submissions#index'

  resources :profiles, only: :show

  resource :pricing
  resources :checkouts
  resources :premium_subscriptions
  get 'success', to: 'checkouts#success'
  resources :webhooks, only: :create
  resources :billings, only: :create
end

app/controllers/profiles_controller.rb
# frozen_string_literal: true

# Finds the profile of user, including any content(Comments, subsmissions) they have created
class ProfilesController < ApplicationController
  def show
    @profile = User.find(params[:id])
    @submissions = @profile.submissions.order(created_at: :desc)
    @comments = @profile.comments.order(created_at: :asc)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_comment.html.erb
<div class="flex items-start p-4 my-4 rounded border">
	<div>
		<p class="font-semibold">
			<%= comment.user.username%>
		</p>
		<p class="prose prose-indigo">
			<%= comment.reply %>
		</p>
		<% if author_of?(comment) %>
			<div class="flex items-end space-x-3">
				<%= link_to "Edit comment", edit_submission_comment_path(comment.submission,comment), class:"text-indigo-600 underline"%>
				<%= button_to "Delete comment", submission_comment_path(comment.submission,comment), class:"text-indigo-600 underline",method: :delete, data: {confirm: "Delete this post?", turbo_method: :delete }%>
			</div>
		<%end %>
	</div>
</div>

app/views/profiles/show.html.erb
<% content_for :primary_content do %>
	<h1 class="pb-6 text-3xl font-bold border-b"> <%= @profile.username %></h1>

	<div class="flex flex-col">
		<div class="flex items-center">
			<%= render_svg "icons/user", styles: "navigation-icon-colored-lg  stroke-none mr-2"%>
			<h3 class="mt-2 mb-3 text-xl font-light">Submissions</h3>
		</div>

		<% if @submissions.any?%>
			<ul class="divide-y">
				<% @submissions.each do |submission|%>
					<%= render "submissions/submission", submission: submission%>
				<%end%>
			</ul>
		<%else%>
			<p>No submissions.</p>
		<%end%>
	</div>

	<hr class="my-6">

	<div class="flex flex-col">
		<div class="flex items-center">
			<%= render_svg "icons/conversation", styles: "navigation-icon-colored-lg stroke-none mr-2"%>
			<h3 class="mt-2 mb-3 text-xl font-light">Comments</h3>
		</div>

		<% if @comments.any?%>
			<ul class="divide-y">
				<% @comments.each do |comment|%>
					<%= render "profiles/comment", comment: comment%>
				<%end%>
			</ul>
		<% else%>
			<p>No comments.</p>
		<%end%>
	</div>

<%end%>

<% content_for :secondary_content do%>
	<div class="text-center">
		<div class="flex justify-center items-center">
			<%= gravatar_for(@profile, class: "rounded-full w-20 h-20")%>
		</div>
		<p class="font-bold"><%= @profile.username %></p>
		<p class="font-extralight text-gray-800">Joined<%= @profile.created_at.to_formatted_s(:nice)%></p>

		<div class="mt-6">
			<% if user_signed_in? %>
				<%= link_to "New submission", new_submission_path, class:"btn btn-indigo block w-full"%>
			<% else%>
				<%= link_to "Login", new_user_session_path, class:"btn btn-outline block w-full mb-4"%>
				<%= link_to "Sign up", new_user_registration_path, class:"btn btn-indigo block w-full"%>
			<%end%>
		</div>
	</div>
<%end%>
<%= render "basic_layout"%>