config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do # rubocop:disable Metrics/BlockLength
  # /sidekiq page

  # authenticate :user, ->(u) { u.admin? } do
  #   mount Sidekiq::Web => '/sideqkic'

  #   namespace :admin do
  #     resources :users
  #     root to: 'users#index'
  #     resources :submissions
  #   end
  # end

  resources :communities do
    resources :subscriptions
  end

  resources :submissions do
    member do
      put 'upvote', to: 'submissions#upvote'
      put 'downvote', to: 'submissions#downvote'
    end

    resources :comments do
      member do
        put 'upvote', to: 'comments#upvote'
        put 'downvote', to: 'comments#downvote'
      end
    end
  end

  get 'submissions/unsubscribe/:unsubscribe_hash' => 'submissions#unsubscribe', as: :comment_unsubscribe
  get :search, controller: :application

  devise_for :users
  root 'submissions#index'

  resources :profiles, only: :show

  resource :pricing
  resources :checkouts
  resources :premium_subscriptions
  get 'success', to: 'checkouts#success'
  resources :webhooks, only: :create
  resources :billings, only: :create
end

app/models/submission.rb
# frozen_string_literal: true

# This represents a submission to a community, making sure the submission is valid.
class Submission < ApplicationRecord
  extend FriendlyId
  include VotesCountable
  include PgSearch::Model

  multisearchable against: %i[title body url]

  belongs_to :user
  belongs_to :community
  has_one_attached :media
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :body, length: { maximum: 8000, minimum: 10 }
  validates :url, url: { allow_blank: true }
  validate :body_or_url
  validate :content_exists

  acts_as_votable

  friendly_id :slug_candidates, use: %i[slugged finders]

  def slug_candidates
    [:title, %i[title id]]
  end

  def should_generate_new_friendly_id?
    if !slug?
      title_changed?
    else
      false
    end
  end

  private

  def body_or_url
    return if url.blank? || body.blank?
    return if url.blank? ^ body.blank?

    errors.add(:base, 'Add a valid URL or text content')
  end

  def content_exists
    return unless url.blank? && body.blank? && !media.attached?

    errors.add(:base, 'Add media to continue')
  end
end

app/controllers/admin/submissions_controller.rb
# frozen_string_literal: true

module Admin
  # Returns all submissions, sorted in ascending order.
  class SubmissionsController < ApplicationController
    def index
      @submissions = Submissions.all.sort
    end
  end
end

app/controllers/submissions_controller.rb
# frozen_string_literal: true

# Handles behaviours relating to a submission
class SubmissionsController < ApplicationController # rubocop:disable Metrics/ClassLength
  include ActionView::RecordIdentifier

  before_action :set_submission, only: %i[show edit update destroy upvote downvote]
  # I feel like unsubscribe could be handled better
  before_action :authenticate_user!, except: %i[index show unsubscribe]

  # GET /submissions or /submissions.json
  def index
    @submissions = if user_signed_in?
                     @feed_title = 'My feed'
                     current_user.subscribed_submissions
                   else
                     @feed_title = 'Select a community'
                     Submission.all
                   end
  end

  # GET /submissions/1 or /submissions/1.json
  def show
    @community = @submission.community
    @subscription = @community.subscriptions.where(user: current_user).first
  end

  # GET /submissions/new
  def new
    @submission = Submission.new
  end

  # GET /submissions/1/edit
  def edit; end

  # Below has not been tested, this fix was covered in lesson 28 - concerns and bugfixes.
  def upvote # rubocop:disable Metrics/MethodLength
    respond_to do |format|
      if current_user.voted_for? @submission
        format.html do
          redirect_back fallback_location: root_path,
                        alert: 'Voted already'
        end
      else
        @submission.upvote_by current_user
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            "#{dom_id(@submission)}_votes_count",
            @submission.total_vote_count
          )
        end
      end
    end
  end

  def downvote # rubocop:disable Metrics/MethodLength
    respond_to do |format|
      if current_user.voted_for? @submission
        format.html do
          redirect_back fallback_location: root_path,
                        alert: 'U mad?'
        end
      else
        @submission.downvote_by current_user
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            "#{dom_id(@submission)}_votes_count",
            @submission.total_vote_count
          )
        end
      end
    end
  end

  def unsubscribe
    User.find_by_unsubscribe_hash(unsubscribe_hash: params[:unsubscribe_hash])
    update(comment_subscription: false)
  end

  # POST /submissions or /submissions.json
  def create # rubocop:disable Metrics/AbcSize,Metrics/MethodLength
    @submission = Submission.new(submission_params)
    @submission.user_id = current_user.id

    respond_to do |format|
      if @submission.save
        format.html do
          redirect_to submission_url(@submission),
                      notice: 'Submission was successfully created.'
        end
        format.json do
          render :show,
                 status: :created,
                 location: @submission
        end
      else
        format.html do
          render :new,
                 status: :unprocessable_entity
        end
        format.json do
          render json: @submission.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /submissions/1 or /submissions/1.json
  def update # rubocop:disable Metrics/MethodLength
    respond_to do |format|
      if @submission.update(submission_params)
        format.html do
          redirect_to submission_url(@submission),
                      notice: 'Submission was successfully updated.'
        end
        format.json do
          ender :show,
                status: :ok,
                location: @submission
        end
      else
        format.html do
          render :edit,
                 status: :unprocessable_entity
        end
        format.json do
          render json: @submission.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /submissions/1 or /submissions/1.json
  def destroy
    @submission.destroy!

    respond_to do |format|
      format.html do
        redirect_to submissions_url,
                    notice: 'Submission was successfully destroyed.'
      end
      format.json do
        head :no_content
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_submission
    @submission = Submission.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def submission_params
    params.require(:submission).permit(:title, :body, :url, :media, :community_id)
  end
end

app/helpers/submissions_helper.rb
# frozen_string_literal: true

# Displays ads, this is the control point for displaying.
# Depending on the users premium status
module SubmissionsHelper
  def inject_feed_ad(index)
    return if user_signed_in? && current_user.subscribed?

    return unless ((index + 1) % 3).zero?

    render partial: 'feed_ad'
  end
end

app/views/submissions/_form.html.erb
<div data-controller="tabs">
	<%= form_with(model: submission, class: "contents") do |form| %>
		<% if submission.errors.any? %>
			<div id="error_explanation" class="p-6 text-red-800 bg-red-50 rounded border border-red-300">
				<h2 class="font-bold leading-tight"><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

				<ul>
					<% submission.errors.each do |error| %>
						<li><%= error.full_message %></li>
					<% end %>
				</ul>
			</div>
		<% end %>
		<div class="mb-6 w-full lg:w-2/5">
			<label for="">Community</label>
			<div class="relative">

				<%= form.select :community_id, Community.all.collect { |v| [v.name,v.id]}, { prompt: "Choose a community"}, {class:"select"}  %>
				<div class="flex absolute right-2 inset-y-5 items-center pointer-events-none">
					<%= render_svg "icons/chevron-down", styles: "fill-current w-4 h-4 text-gray-500" %>
				</div>
			</div>
		</div>
		<label for="submission_type">Submission type</label>
		<nav role="submission type" class="mb-6">
			<ul class="grid grid-cols-1 gap-0 border divide-y shadow-sm lg:divide-x lg:grid-cols-3">
				<li>
					<a href="" data-action="click->tabs#toggle" data-tabs-target="button" data-tab-id="text" class="flex justify-center items-center p-4 group hover:text-indigo-600">
						<%= render_svg "icons/text", styles:"group-hover:text-indigo-600 text-gray-500 w-5 h-5 fill-current mr-2" %>
						Text
					</a>
				</li>
				<li>
					<a  href="" data-action="click->tabs#toggle" data-tabs-target="button" data-tab-id="media" class="flex justify-center items-center p-4 group hover:text-indigo-600">
						<%= render_svg "icons/image", styles:"group-hover:text-indigo-600 text-gray-500 w-5 h-5 fill-current mr-2" %>
						Image/Video
					</a>
				</li>

				<li>
					<a href="" data-action="click->tabs#toggle" data-tabs-target="button" data-tab-id="url" class="flex justify-center items-center p-4 group hover:text-indigo-600">
						<%= render_svg "icons/link", styles:"group-hover:text-indigo-600 text-gray-500 w-5 h-5 fill-current mr-2" %>
						URL
					</a>
				</li>
			</ul>
		</nav>
		<div class="my-5">
			<%= form.label :title %>
			<%= form.text_field :title, class: "input"%>
		</div>

		<div class="my-5" data-tabs-target="text">
			<%= form.label :body %>
			<%= form.text_field :body, class: "input min-h-[200px]" %>
		</div>

		<div data-tabs-target="url" class="hidden my-5">
			<%= form.label :url %>
			<%= form.text_field :url, class: "input"%>
		</div>

		<div data-tabs-target="media" class="hidden my-5">
			<%= form.label :media do %>
				<span class="block mb-1">Attach an Image/Video</span>
				<%= form.file_field :media, class: "inline-flex items-center rounded-md bg-indigo-50 px-2 py-1 text-xs font-medium text-indigo-700 ring-2 ring-inset ring-indigo-600/20"%>
			<% end%>
		</div>

		<div class="inline">
			<%= form.submit class: "btn btn-indigo" %>
		</div>
	<% end %>
</div>

app/views/submissions/_guidelines.html.erb
<h3 class="mb-4 font-bold">Webbit posting Guidelines</h3>
<ol class="p-0 text-sm leading-loose list-none divide-y">
	<li class="pt-1">Behave</li>
	<li class="pt-1">Proper British etiquette</li>
	<li class="pt-1">Thy shan't omit thee thoughts about Queen Elizibth</li>
	<li class="pt-1">Duplicate posts will result in a permanent suspension. Be precarious</li>
</ol>

app/views/submissions/_submission.html.erb
<li id="<%= dom_id submission %>">
	<div class="flex flex-wrap items-start py-3">
		<%= render "shared/voting" , is_comment: false, content: submission, upvote: upvote_submission_path(submission), downvote: downvote_submission_path(submission) %>
		<% if submission.media.attached? %>
			<div class="w-2/12">
				<%= link_to submission do %>

					<% if submission.media.video?%>
						<%= video_tag submission.media%>
					<%else%>
						<%= image_tag submission.media.variant(resize_to_fit: [200,200]), alt: submission.title, class: "rounded-sm "%>
					<%end%>
				<%end %>
			</div>
		<% end %>

		<div class="flex-1 <%= "pl-4" if submission.media.attached?  %>">
			<h3 class="flex flex-wrap items-center mb-1 text-xl font-semibold text-pink-600 hover:text-indigo-600">
				<%= link_to submission.title, submission, class: "no-underline"%>
				<% if submission.url? %>
					<span class= "pl-2 font-mono text-xs font-normal tracking-tighter text-indigo-400">
						<%= truncate(submission.url, length: 18 ) %>
					</span>
				<% end%>
			</h3>
			<p class="mb-2 font-mono text-sm text-gray-600 group hover:text-indigo-600">
				w/<%= link_to submission.community.name, community_path(submission.community), class:"group-hover:text-indigo-600"%>
			</p>
			<% if submission.body? %>
				<div class="text-sm text-gray-900">
					<%= truncate(submission.body, length: 140 ) %>
				</div>
			<% end %>
			<div class="flex flex-wrap items-center">
				<div class="flex-1 justify-between mt-3">
					<%= link_to submission_path(submission, anchor:"post_comment_section"), class:"flex items-center space-x-3 group" do %>
						<%= render_svg "icons/conversation", styles:" group-hover:text-indigo-600 text-gray-500 w-4 h-4 fill-current"%>
						<p class="group-hover:text-indigo-600">
							<%= pluralize(submission.comments.size, 'comment')%>
						</p>
					<%end %>

				</div>

				<% if author_of?(submission)%>
					<div class="flex flex-wrap items-center pt-2">
						<%= link_to edit_submission_path(submission), class:"no-underline mr-2" do %>
							<%= render_svg "icons/edit", title: "Edit", styles: "fill-current text-gray-400 w-5 h-5 hover:text-indigo-500"%>
						<% end%>
						<%= link_to submission_path(submission), method: :delete, data: {confirm: "Delete this post?", turbo_method: :delete }, class:"no-underline block mt-px" do %>
							<%= render_svg "icons/delete", title: "Delete", styles: "fill-current text-gray-400 w-5 h-5 hover:text-indigo-500"%>
						<% end%>
					</div>
				<% end%>
			</div>
		</div>
	</div>
</li>

app/views/submissions/edit.html.erb
<% content_for :primary_content do%>
	<div class="flex flex-col">
		<div class="w-6/12">
			<%= link_to "<- Back", submissions_path, class: "pt-3 pl-0 btn-xs bold btn" %>
		</div>
		<h1 class="text-4xl font-bold">Editing submission</h1>
	</div>

	<%= render "form", submission: @submission %>
<% end%>

<% content_for :secondary_content do%>
	<%= render "guidelines" %>
<% end%>

<%= render "basic_layout"%>

app/views/submissions/index.html.erb
<% title "Submissions"%>
<% content_for :community_label, @feed_title%>
<% content_for :primary_content do %>
	<% if @submissions.any? %>
		<div id="submissions">
			<ul class="list-none divide-y">
				<% @submissions.each_with_index do |submission, index| %>
					<%= inject_feed_ad(index) %>
					<%= render submission%>

				<% end%>
			</ul>
		</div>
	<% else %>
		<div class="p-10 text-center">
			<div class="flex justify-center list-none">
				<%= render_svg "icons/empty" %>
			</div>
			<p class="mb-5">No submissions have been made :'(</p>
			<%= link_to "Create a new post", new_submission_path, class: "btn btn-indigo"%>
		</div>
	<% end %>
<% end %>

<% content_for :secondary_content do%>
	<div class="flex flex-col p-4">
		<% if user_signed_in? %>
			<h3 class="text-lg font-bold">Welcome, <%= current_user.username%> </h3>
			<%= link_to "New submission", new_submission_path, class:"btn btn-indigo" %>
			<div class="py-2 grow">
			</div>
			<%= link_to "New community", new_community_path, class:"btn btn-outline" %>
		<% else%>
			<%= image_tag "illustration.svg", class:"max-w-full"%>
			<h3 class="text-lg font-bold">
				Explore
			</h3>

			<p class="text-sm text-gray-600">
				Find a community for you!
			</p>
			<%= link_to "#", class:" btn btn-indigo my-2 block text-center"%>
		<% end%>
	</div>
<% end %>

<%=  render "basic_layout" %>

app/views/submissions/new.html.erb
<% content_for :community_label, "New Post"%>

<% content_for :primary_content do%>
	<h1 class="mb-6 text-4xl font-bold">New submission</h1>

	<%= render "form", submission: @submission %>
<% end%>

<% content_for :secondary_content do%>
	<%= render "guidelines" %>
<% end%>

<%= render "basic_layout"%>

app/views/submissions/show.html.erb
<% title @submission.title%>

<%= content_for :community_label, @submission.community.name %>
<%= render "communities/header", community: @submission.community%>

<%= content_for :primary_content do %>
	<div class="flex flex-row justify-between">
		<%# <%= render "submissions/voting", submission: @submission %>
		<%= render "shared/voting" , is_comment: false, content: @submission, upvote: upvote_submission_path(@submission), downvote: downvote_submission_path(@submission) %>
		<div class="flex-1">
			<p class="text-sm text-gray-600">Posted By: <%= link_to @submission.user.username, profile_path(@submission.user), class:"underline"%> <%= time_ago_in_words(@submission.created_at) + " ago" %></p>
			<h1 class="mb-6 text-3xl font-bold"><%= @submission.title%></h1>

			<% if @submission.media.attached?%>
				<% if @submission.media.video?%>
					<%= video_tag @submission.media%>
				<%else%>
					<%= image_tag @submission.media, alt: @submission.title, class: "rounded-sm "%>
				<%end%>
			<%end%>

			<% if @submission.body? %>
				<div class="prose prose-lg prose-indigo">
					<%= simple_format @submission.body%>
				</div>
			<% end%>

			<% if @submission.url?%>
				<%= link_to truncate(@submission.url, length:100), @submission.url, class:"font-mono text-indigo-500 hover:underline", target: :_blank%>
			<% end%>
			<div class="flex items-center mt-6 space-x-5">
				<div class="flex items-center space-x-3">
					<%= render_svg "icons/conversation", styles:"w-5 fill-current text-gray-500 mt-1"%>
					<p id="<%= dom_id(@submission)%>_comment_count">
						<%= pluralize(@submission.comments.size, ' comment')%>
					</p>

				</div>

				<% if author_of?(@submission) %>
					<%= link_to  edit_submission_path(@submission), class:"group" do%>
						<span class="sr-only">Edit this submission</span>
						<%= render_svg "icons/edit", styles: "w-5 fill-current group-hover:text-indigo-600 text-gray-500"%>
					<% end%>
					<%= button_to submission_path(@submission),  method: :delete, data: {confirm: "Delete this post?", turbo_method: :delete }, class:"group" do %>
						<span class="sr-only">Delete this submission</span>
						<%= render_svg "icons/delete", styles:"w-5 fill-current group-hover:text-indigo-600  text-gray-500 mt-1"%>
					<% end%>
				<% end %>
			</div>
		</div>
	</div>
	<div class="pt-6 mt-6 border-t border-gray-300">

		<% if user_signed_in?%>
			<div id="<%= dom_id(@submission)%>_comments">
				<%= render "comments/form", comment: Comment.new%>
			</div>
		<% else%>
			<div class="p-4 mt-6 text-center bg-gray-50 rounded">
				<%= link_to "Login to reply",new_user_session_path, class: "text-indigo-600 underline"%>
			</div>
		<% end%>
		<%# Add no comments made fluff %>
		<h3 id="post_comment_section"class="mt-6 font-bold">Comments</h3>
		<div id="<%= dom_id(@submission)%>_comments_form">
			<% if @submission.comments.any? %>
				<%= render @submission.comments %>
			<%end %>
		</div>
	</div>
<%end%>

<%= content_for :secondary_content do %>
	<%= render "communities/sidebar", community: @submission.community%>
<%end%>

<%= render "basic_layout"%>

app/views/submissions/unsubscribe.html.erb
<div class="p-10 mx-auto my-16 max-w-md text-center bg-white rounded-lg shadow-xl">
	<h2 class="mb-6 text-3xl font-bold">Unsubscribed!</h2>

	<%= link_to "Return to Webbit", root_path, class: "btn btn-indigo" %>
</div>

app/views/submissions/upvote.turbo_stream.html.erb
<%=  turbo_stream.replace dom_id(@submission) do %>
	<%= render "comments/comment", comment: @comment%>
<%end%>